import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import AuthSessionProvider from "./SessionProvider";
import CustomApolloProvider from "./ApolloProvider";

import { ToastProvider } from "@/context/ToastContext";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Fournit le contexte NextAuth à toute l'app (fixe useSession)
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Fournit les contextes Auth et Apollo à toute l’app */}
        <AuthSessionProvider>
          <CustomApolloProvider>
            {/* Fournit le contexte Toast global à toute l'app */}
            <ToastProvider>
              {children}
            </ToastProvider>
          </CustomApolloProvider>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
